module.exports = [
  "Abouriou",
  "Abrustine",
  "Absinthe",
  "Acadie Blanc",
  "Acolon",
  "Agiorgitiko",
  "Aglianico",
  "Aglianico-Piedirosso",
  "Ahmeur bou Ahmeur",
  "Aidani",
  "Airen",
  "Aladasturi",
  "Alarijen",
  "Albalonga",
  "Albana",
  "Albanella",
  "Albarello Blanca",
  "Albarin Blanco",
  "Albarino (Alvarinho)",
  "Albarola",
  "Albarola-Bosco-Vermentino",
  "Albarossa",
  "Albillo Krimskii (Rachuli Tetra)",
  "Albillo",
  "Alcohol-Free",
  "Aleatico",
  "Alexandrouli",
  "Alfrocheiro Preto",
  "Alfrocheiro Preto-Tinta Roriz-Touriga",
  "Alfrocheiro Preto-Touriga",
  "Alibernet",
  "Alicante Bouschet",
  "Alicante Bouschet-Aragonez",
  "Alicante Bouschet-Aragonez-Trincadeira",
  "Alicante Bouschet-Touriga",
  "Alicante Ganzin",
  "Aligote",
  "Alphonse Lavallee",
  "Altesse",
  "Alvarelhao",
  "Amigne",
  "Ancellotta",
  "Andre",
  "Antao Vaz",
  "Antao Vaz-Arinto (Pederna)",
  "Aragonez (Tinta Roriz)-Castelao",
  "Aramon",
  "Aranel",
  "Arbane",
  "Arbois",
  "Areni Noir",
  "Argaman",
  "Argant",
  "Arinarnoa",
  "Arinto (Pederna)",
  "Arinto (Pederna)-Fernao Pires",
  "Arinto (Pederna)-Loureiro",
  "Arneis",
  "Arriloba",
  "Arrufiac",
  "Aspiran",
  "Assyrtico",
  "Athiri",
  "Aubin Vert",
  "Aubun",
  "Aurore",
  "Auxerrois",
  "Avana",
  "Avarengo",
  "Avesso",
  "Avgoustiatis",
  "Azal Branco",
  "Azal Tinto",
  "Babeasca Neagra",
  "Babic",
  "Bacchus",
  "Bachet",
  "Baco Blanc",
  "Baco Noir",
  "Baga",
  "Baijiu",
  "Baltica",
  "Barbarossa",
  "Barbera",
  "Barbera-Bonarda (Croatina)",
  "Barbera-Dolcetto-Nebbiolo",
  "Barbera-Nebbiolo",
  "Barbera-Sangiovese",
  "Baroque",
  "Barsaglina",
  "Batiki",
  "Beaunoir",
  "Beer",
  "Bellone Bianco",
  "Bequignol",
  "Bervedino",
  "Bianchello (Biancame)",
  "Bianchetta Genovese",
  "Bianco d'Alessano",
  "Bianco d'Alessano-Verdeca",
  "Biancolella",
  "Biancone",
  "Biancu Gentile",
  "Bical",
  "Bigolona",
  "Bitters",
  "Black Monukka",
  "Black Spanish (Lenoir)",
  "Blanc du Bois",
  "Blanqueiron",
  "Blauburger",
  "Blauer Wildbacher",
  "Blaufrankisch (Lemberger)",
  "Blaufrankisch-Cabernet",
  "Blaufrankisch-Cabernet-Merlot",
  "Blaufrankisch-Zweigelt",
  "Bobal Blanco",
  "Bobal",
  "Bogazkere",
  "Bogazkere-Okuzgozu",
  "Bogdanusa",
  "Bombino Bianco",
  "Bombino Nero",
  "Bonarda Piemontese",
  "Bonarda-Malbec",
  "Bondola",
  "Bordeaux Blend Red",
  "Bordeaux Blend White",
  "Bosco",
  "Bourboulenc",
  "Bouvier",
  "Brachetto",
  "Brandy",
  "Braquet",
  "Brauner Veltliner",
  "Brianna",
  "Bronner",
  "Bronx",
  "Brun Fourca",
  "Brunal",
  "Bual",
  "Bukettraube",
  "Burger",
  "Cab Franc-Gamay-Malbec",
  "Cabernet Blanc",
  "Cabernet Cubin",
  "Cabernet Dorio",
  "Cabernet Dorsa",
  "Cabernet Franc",
  "Cabernet Franc-Cabernet Sauvignon",
  "Cabernet Franc-Gamay",
  "Cabernet Franc-Malbec",
  "Cabernet Franc-Merlot",
  "Cabernet Franc-Pinot Noir",
  "Cabernet Gernischt",
  "Cabernet Jura",
  "Cabernet Mitos",
  "Cabernet Moravia",
  "Cabernet Pfeffer",
  "Cabernet Sauvignon",
  "Cabernet Sauvignon-Carignan",
  "Cabernet Sauvignon-Carmenere",
  "Cabernet Sauvignon-Cinsaut",
  "Cabernet Sauvignon-Malbec",
  "Cabernet Sauvignon-Merlot",
  "Cabernet Sauvignon-Pinot Noir",
  "Cabernet-Carignan-Grenache",
  "Cabernet-Carignan-Syrah",
  "Cabernet-Grenache-Merlot-Syrah",
  "Cabernet-Grenache-Mourvedre-Syrah",
  "Cabernet-Grenache-Syrah",
  "Cabernet-Malbec-Syrah",
  "Cabernet-Merlot-Montepulciano",
  "Cabernet-Merlot-Sangiovese",
  "Cabernet-Merlot-Syrah",
  "Cabernet-Merlot-Tempranillo",
  "Cabernet-Merlot-Zinfandel",
  "Cabernet-Merlot-Zweigelt",
  "Cabernet-Montepulciano",
  "Cabernet-Mourvedre-Syrah",
  "Cabernet-Nero d'Avola",
  "Cabernet-Petit Verdot",
  "Cabernet-Pinotage",
  "Cabernet-Sangiovese",
  "Cabernet-Sangiovese-Syrah",
  "Cabernet-Syrah-Tempranillo",
  "Cabernet-Syrah-Zinfandel",
  "Cabernet-Syrah/Shiraz",
  "Cabernet-Tannat",
  "Cabernet-Tempranillo",
  "Cabernet-Zinfandel",
  "Cabernets-Grolleau",
  "Cachaca",
  "Cagnulari",
  "Caino Tinto",
  "Cal Karasi",
  "Caladoc",
  "Calbanesco",
  "Calitor",
  "Callet",
  "Calzin",
  "Camaralet de Lasseube",
  "Camarate",
  "Canaiolo Bianco",
  "Canaiolo",
  "Canocazo",
  "Carcajolo Blanc",
  "Carcajolo Nero",
  "Caricalasino",
  "Carignan (Carinena)",
  "Carignan Blanc",
  "Carignan Gris",
  "Carignan-Grenache-Syrah",
  "Carignan-Grenache-Tempranillo",
  "Carignan-Merlot",
  "Carignan-Syrah",
  "Carinena-Garnacha",
  "Carmenere",
  "Carmenere-Syrah",
  "Carmine",
  "Carminoir",
  "Carnelian",
  "Carrasquin",
  "Carricante",
  "Carricante-Catarratto",
  "Casavecchia",
  "Casetta",
  "Cassady",
  "Castelao",
  "Castelao-Touriga",
  "Catarratto",
  "Catarratto-Chardonnay",
  "Catarratto-Grillo-Inzolia",
  "Catarratto-Inzolia",
  "Catawba",
  "Cava Blend",
  "Cayetana",
  "Cayuga",
  "Cecubo",
  "Centesimino (Savignon Rosso)",
  "Centurion",
  "Cerceal",
  "Cereza",
  "Cesanese",
  "Cesar",
  "Cetinka",
  "Chambourcin",
  "Champagne Blend",
  "Chancellor",
  "Charbono (Bonarda)",
  "Chardonel",
  "Chardonnay Musque",
  "Chardonnay Rose",
  "Chardonnay",
  "Chardonnay-Chenin Blanc",
  "Chardonnay-Colombard",
  "Chardonnay-Garganega",
  "Chardonnay-Gewurztraminer",
  "Chardonnay-Muscat",
  "Chardonnay-Pinot Blanc",
  "Chardonnay-Pinot Blanc-Pinot Noir",
  "Chardonnay-Pinot Gris",
  "Chardonnay-Pinot Noir",
  "Chardonnay-Riesling",
  "Chardonnay-Roussanne",
  "Chardonnay-Roussanne-Viognier",
  "Chardonnay-Sauvignon Blanc",
  "Chardonnay-Sauvignon-Semillon",
  "Chardonnay-Savagnin",
  "Chardonnay-Semillon",
  "Chardonnay-Torrontes",
  "Chardonnay-Verdelho",
  "Chardonnay-Vermentino",
  "Chardonnay-Viognier",
  "Chardonnay-Viura",
  "Chardonnay-Xarel-lo",
  "Charmont",
  "Chasan",
  "Chasselas",
  "Chelois",
  "Chenanson",
  "Chenel",
  "Chenin Blanc",
  "Chianti Blend",
  "Cider",
  "Cienna",
  "Ciliegiolo",
  "Cinsaut",
  "Cinsaut-Grenache",
  "Cinsaut-Grenache-Mourvedre",
  "Cinsaut-Grenache-Syrah",
  "Cinsaut-Mourvedre",
  "Cinsaut-Mourvedre-Syrah",
  "Cinsaut-Pinotage",
  "Cinsaut-Syrah",
  "Cividino",
  "Clairette",
  "Clairette-Marsanne",
  "Clairette-Marsanne-Ugni",
  "Clairette-Muscat",
  "Clairette-Rolle",
  "Clairette-Ugni Blanc",
  "Claret de Gers",
  "Clinton",
  "Cococciola",
  "Coda di Volpe",
  "Codega do Larinho",
  "Colombard",
  "Colombard-Folle-Ugni",
  "Colombard-Ugni Blanc",
  "Colorino",
  "Completer",
  "Concord",
  "Corinto Nero",
  "Cornalin",
  "Cornifesto",
  "Corot Noir",
  "Cortese",
  "Corvina",
  "Corvina-Rondinella",
  "Corvinone",
  "Couderc Noir",
  "Counoise",
  "Courbu Blanc",
  "Criolla Grande",
  "Croatina",
  "Crouchen (Cape Riesling)",
  "Crovino",
  "Cserszegi Fuszeres",
  "Cygne Blanc",
  "Dafni",
  "Damaschino",
  "Dameron",
  "Darnekusa",
  "De Chaunac",
  "Debina",
  "Debit",
  "Delaware",
  "Diamond",
  "Dimiat",
  "Dindarella",
  "Diolinoir",
  "Dobricic",
  "Dolcetto",
  "Domina",
  "Dona Blanca",
  "Donzelinho Branco",
  "Doral",
  "Dornfelder",
  "Dorona di Venezia",
  "Doux d'Henry",
  "Dunkelfelder",
  "Duras",
  "Duras-Fer Servadou",
  "Duras-Fer-Syrah",
  "Duras-Syrah",
  "Durella",
  "Durif-Shiraz",
  "Durize",
  "Dzvelshava",
  "Early Muscat",
  "Eau-de-Vie",
  "Edelweiss",
  "Edelzwicker Blend",
  "Egiodola",
  "Ehrenfelser",
  "Elbling",
  "Elvira",
  "Emerald Riesling",
  "Emir",
  "Enantio",
  "Encruzado",
  "Erbaluce",
  "Espadeiro",
  "Etraire de l'Adui",
  "Eyholzer",
  "Ezerjo",
  "Faber",
  "Falanghina",
  "Fer Servadou",
  "Fernao Pires",
  "Feteasca Alba",
  "Feteasca Neagra",
  "Feteasca Regala",
  "Fiano",
  "Findling",
  "Flora",
  "Florental",
  "Foglia Tonda",
  "Fogoneu",
  "Folgasao",
  "Folle Blanche",
  "Forastera",
  "Fortana",
  "Franc Noir de la Haute-Saone",
  "Francavilla",
  "Francusa",
  "Frappato",
  "Frappato-Nero d'Avola",
  "Freisa",
  "Freisamer",
  "Friulano",
  "Frontenac Gris",
  "Frontenac",
  "Fruhburgunder",
  "Fruhroter Veltliner",
  "Fruit and Spiced Wine",
  "Fumin",
  "Furmint",
  "Gaglioppo",
  "Gaidoura",
  "Gamaret",
  "Gamaret-Garanoir",
  "Gamaret-Garanoir-Pinot Noir",
  "Gamay",
  "Gamay-Grolleau Noir",
  "Gamay-Pinot Noir",
  "Gamay-Poulsard",
  "Gamba di Pernice",
  "Garanoir",
  "Garganega",
  "Garganega-Pinot Grigio",
  "Garnacha-Tempranillo",
  "Garrido",
  "Gellewza",
  "Genever (Jenever)",
  "Gewurztraminer",
  "Gewurztraminer-Riesling",
  "Gin",
  "Girgentina",
  "Giro",
  "Glera (Prosecco)",
  "Godello",
  "Goldburger",
  "Goldriesling",
  "Gouais Blanc",
  "Gouveio",
  "Graciano",
  "Grechetto Bianco",
  "Grechetto Rosso",
  "Greco Bianco",
  "Greco Nero",
  "Green Hungarian",
  "Grenache (Garnacha)",
  "Grenache Blanc",
  "Grenache Blanc-Grenache Gris",
  "Grenache Blanc-Vermentino",
  "Grenache Gris",
  "Grenache-Merlot-Syrah",
  "Grenache-Mourvedre",
  "Grenache-Mourvedre-Syrah",
  "Grenache-Sangiovese",
  "Grenache-Syrah",
  "Grignolino",
  "Grillo",
  "Gringet",
  "Grk",
  "Grolleau Gris",
  "Grolleau Noir",
  "Groppello",
  "Gros Manseng",
  "Gros Manseng-Petit Manseng",
  "Gros Manseng-Sauvignon Blanc",
  "Gros Verdot",
  "Gruner Veltliner",
  "Gutenborner",
  "Harslevelu",
  "Helfensteiner",
  "Heroldrebe",
  "Himbertscha",
  "Hondarrabi Beltza",
  "Hondarrabi Zuri",
  "Honey",
  "Humagne Blanche",
  "Humagne Rouge",
  "Huxelrebe",
  "Inzolia",
  "Irsay Oliver",
  "Isabella",
  "Ives",
  "Izsaki",
  "Jacquere",
  "Jampal",
  "Johanniter",
  "Joubertin",
  "Juan Garcia",
  "Juhfark",
  "Jurancon Blanc",
  "Jurancon Noir (Folle Noire)",
  "Juwel",
  "Kabar",
  "Kadarka Blau",
  "Kalecik Karasi",
  "Kanzler",
  "Karasakiz",
  "Katsano",
  "Keduretuli (Mujuretuli)",
  "Kekmedoc",
  "Keknyelu",
  "Kerner",
  "Koshu",
  "Kotsifali",
  "Kotsifali-Mandilaria",
  "Koverszolo (Grasa de Cotnari)",
  "Kovidinka",
  "Krakuna",
  "Krassato",
  "Kuldzhinskii (Kouldjinka)",
  "La Crescent",
  "La Crosse",
  "Lacrima",
  "Lado",
  "Lagorthi",
  "Lagrein",
  "Lambrusco",
  "Landot Noir",
  "Lasin",
  "Lauzet",
  "Leanyka",
  "Lemberger-Trollinger",
  "Len de l'El",
  "Len de l'El-Mauzac",
  "Leon Millot",
  "Liatiko",
  "Limnio",
  "Liqueur",
  "Liqueur-Anise",
  "Liqueur-Chocolate",
  "Liqueur-Coffee",
  "Liqueur-Cream",
  "Liqueur-Egg",
  "Liqueur-Fruit",
  "Liqueur-Herb-Spice",
  "Liqueur-Nut",
  "Liqueur-Toffee",
  "Listan Negro",
  "Lledoner Pelut",
  "Loureiro",
  "Lucie Kuhlmann",
  "Luglienga Bianca",
  "Lumassina",
  "Macabeo (Viura)",
  "Macabeo-Parellada-Xarel-lo",
  "Maceratino",
  "Madeleine Angevine",
  "Magliocco Canino",
  "Majarca Alba",
  "Malagousia",
  "Malbec",
  "Malbec-Merlot",
  "Malbec-Merlot-Tannat",
  "Malbec-Pinot Noir",
  "Malbec-Syrah",
  "Malbo Gentile",
  "Malvar",
  "Malvasia Bianca",
  "Malvasia Nera",
  "Malvasia Nera-Negroamaro",
  "Malvasia di Candia",
  "Malvasia",
  "Malvasia-Trebbiano",
  "Mandilaria (Amorghiano)",
  "Mansengs-Petit Courbu",
  "Manto Negro",
  "Mantonico Bianco",
  "Manzoni Bianco",
  "Marastina",
  "Maratheftiko",
  "Marechal Foch",
  "Marmajuelo",
  "Marquette",
  "Marsanne",
  "Marsanne-Roussanne",
  "Marselan",
  "Marzemino",
  "Matrassa",
  "Maturana Blanca",
  "Maturana Tinta",
  "Mauzac",
  "Mavro",
  "Mavrodaphne",
  "Mavrotragano",
  "Mavrud",
  "Mayolet",
  "Melara",
  "Melnik",
  "Melody",
  "Melon Queue Rouge",
  "Melon de Bourgogne",
  "Mencia",
  "Merille",
  "Meritage",
  "Merlot Blanc",
  "Merlot",
  "Merlot-Montepulciano",
  "Merlot-Nero d'Avola",
  "Merlot-Sagrantino-Sangiovese",
  "Merlot-Sangiovese",
  "Merlot-Sangiovese-Syrah",
  "Merlot-Syrah",
  "Merlot-Tannat",
  "Merlot-Tempranillo",
  "Merseguera",
  "Merwah",
  "Merzling",
  "Mezcal",
  "Milgranet",
  "Minhota",
  "Minnella",
  "Mischurnitz",
  "Miss Blanc",
  "Mission",
  "Molinara",
  "Moll",
  "Monastrell-Tempranillo",
  "Mondeuse Blanche",
  "Mondeuse Noire",
  "Monica",
  "Monstericco",
  "Montepulciano",
  "Montepulciano-Sangiovese",
  "Montepulciano-Syrah",
  "Montonega",
  "Montuni",
  "Moravia Agria",
  "Moreto",
  "Morio-Muskat",
  "Moristel",
  "Moscato Giallo",
  "Moscato Rosa",
  "Moschofilero",
  "Moschofilero-Roditis",
  "Mourisco Tinto",
  "Mourvedre (Monastrell)",
  "Mourvedre-Syrah",
  "Mtsvani",
  "Muller-Thurgau",
  "Muscadelle",
  "Muscadine",
  "Muscardin",
  "Muscat Bailey A",
  "Muscat Blanc a Petits Grains",
  "Muscat Hamburg (Muskat Trollinger)",
  "Muscat Ottonel",
  "Muscat of Alexandria",
  "Muscat",
  "Muscat-Viognier",
  "Muskat Moravsky",
  "Narince",
  "Nascetta",
  "Nasco",
  "Nebbiolo",
  "Negoska",
  "Negrara",
  "Negrette",
  "Negroamaro",
  "Negroamaro-Primitivo",
  "Nerello Cappuccio",
  "Nerello Cappuccio-Nerello Mascalese",
  "Nerello Mascalese",
  "Nero Buono",
  "Nero d'Avola",
  "Nero d'Avola-Syrah",
  "Neuburger",
  "New-make Spirit",
  "Neyret",
  "Niagara",
  "Nielluccio-Sciaccarello",
  "Nincusa",
  "Noah",
  "Noblessa",
  "Nobling",
  "Nocera",
  "Noiret",
  "Norton",
  "Nosiola",
  "Nuragus",
  "Obaideh",
  "Ojaleshi",
  "Okuzgozu",
  "Olivella",
  "Ondenc",
  "Opthalmo",
  "Optima",
  "Orion",
  "Orleans",
  "Ortega",
  "Ortrugo",
  "Orvieto Blend",
  "Oseleta",
  "Osiris",
  "Osteiner",
  "Palas",
  "Palava",
  "Pallagrello Bianco",
  "Pallagrello Nero",
  "Palomino",
  "Pamid",
  "Pampanuto",
  "Papazkarasi",
  "Parc",
  "Parellada",
  "Parraleta",
  "Pascal Blanc",
  "Passerina",
  "Passerina-Pecorino-Trebbiano",
  "Pecorino",
  "Pedral",
  "Pedro Ximenez",
  "Pelaverga",
  "Peloursin",
  "Perdea",
  "Perle",
  "Perricone",
  "Persan",
  "Petit Bouschet",
  "Petit Courbu",
  "Petit Manseng",
  "Petit Meslier",
  "Petit Rouge",
  "Petit Verdot",
  "Petite Arvine",
  "Petite Sirah (Durif)",
  "Petite Sirah-Syrah-Zinfandel",
  "Petite Sirah-Zinfandel",
  "Petroulianos",
  "Peurion",
  "Phoenix",
  "Piccola Nera",
  "Picolit",
  "Picpoul Noir",
  "Picpoul",
  "Piculit Neri",
  "Piedirosso",
  "Pignerol",
  "Pignola",
  "Pignoletto",
  "Pignolo",
  "Pinard",
  "Pineau d'Aunis",
  "Pinella (Pinello)",
  "Pinot Blanc",
  "Pinot Blanc-Pinot Noir",
  "Pinot Grigio",
  "Pinot Grigio-Zibibbo",
  "Pinot Gris",
  "Pinot Gris-Sauvignon Blanc",
  "Pinot Meunier",
  "Pinot Meunier-Pinot Noir",
  "Pinot Noir",
  "Pinot Noir-Syrah",
  "Pinot Noir-Zweigelt",
  "Pinot d'Alsace",
  "Pinot-Poulsard-Trousseau",
  "Pinotage",
  "Pinotage-Shiraz",
  "Pisco",
  "Planta Fina de Pedralba",
  "Planta Nova",
  "Plantet",
  "Plavac Mali",
  "Plavac Veli",
  "Plavina",
  "Plyto",
  "Pollera Nera",
  "Pontac",
  "Port Blend Red",
  "Port Blend White",
  "Portan",
  "Portugieser",
  "Portuguese Red Blend",
  "Portuguese White Blend",
  "Posip",
  "Poulsard",
  "Precoce de Malingre",
  "Premetta",
  "Premixed Drinks",
  "Prie Blanc",
  "Prieto Picudo",
  "Primitivo",
  "Prokupac",
  "Prunelard Blanc",
  "Prunelard Noir",
  "Pugnitello",
  "Quagliano",
  "Rabo de Ovelha",
  "Raboso",
  "Raffiat de Moncade",
  "Ramisco",
  "Rare Red Blend",
  "Rare Rose Blend",
  "Rare White Blend",
  "Rassegui",
  "Ratafia",
  "Rathay",
  "Rauschling",
  "Ravat Blanc",
  "Ravat Vignoles",
  "Rayon d'Or",
  "Rebo",
  "Refosco",
  "Regent",
  "Regner",
  "Reichensteiner",
  "Reze",
  "Ribolla",
  "Rieslaner",
  "Riesling",
  "Riesling-Silvaner",
  "Rioja Red Blend",
  "Rioja White Blend",
  "Rkatsiteli",
  "Roditis",
  "Roesler",
  "Rolle-Ugni Blanc",
  "Romorantin",
  "Rondinella",
  "Rondo",
  "Roscetto",
  "Rossara",
  "Rossese",
  "Rossola Nera",
  "Rotberger",
  "Roter Gutedel",
  "Roter Riesling",
  "Roter Traminer (Savagnin Rose)",
  "Roter Veltliner",
  "Rotgipfler",
  "Rougeon",
  "Roussanne",
  "Roussanne-Viognier",
  "Royalty",
  "Rubienne",
  "Rubin Bolgarskii",
  "Rubired",
  "Ruby Cabernet",
  "Ruche",
  "Rufete (Tinta Pinheira)",
  "Rum",
  "Sacy",
  "Sagrantino",
  "Sagrantino-Sangiovese",
  "Saint-Croix",
  "Saint-Jeannet",
  "Saint-Macaire",
  "Saint-Pepin",
  "Sake",
  "Samtrot",
  "Sangiovese",
  "Sangiovese-Syrah",
  "Sankt Laurent",
  "Santa Maria",
  "Saperavi",
  "Sauvignon Blanc",
  "Sauvignon Blanc-Semillon",
  "Sauvignon Blanc-Ugni Blanc",
  "Sauvignon Blanc-Verdejo",
  "Sauvignon Blanc-Vermentino",
  "Sauvignon Blanc-Viognier",
  "Sauvignon Gris",
  "Savagnin",
  "Savatiano",
  "Scheurebe",
  "Schiava",
  "Schioppettino",
  "Schnapps",
  "Schonburger",
  "Sciaccarello (Mammolo)",
  "Scuppernong",
  "Semidano",
  "Semillon",
  "Semillon-Rolle",
  "Sercial",
  "Seyval Blanc",
  "Sgavetta",
  "Sherry Blend",
  "Shiraz",
  "Shochu",
  "Sideritis",
  "Siegerrebe",
  "Silcher",
  "Silvaner",
  "Siria (Roupeiro)",
  "Skrlet",
  "Smederevka",
  "Soave Blend",
  "Soju",
  "Solaris",
  "Sotol",
  "Southern Rhone Red Blend",
  "Southern Rhone White Blend",
  "Spergola",
  "Stavroto",
  "Steuben",
  "Sultana",
  "Sumoll Blanco",
  "Sumoll",
  "Susumaniello",
  "Symphony",
  "Syrah",
  "Syrah-Tempranillo",
  "Syrah-Touriga",
  "Syrah-Viognier",
  "Syrah-Zinfandel",
  "Szagos Feher",
  "Taminga",
  "Tannat",
  "Tarrango",
  "Tavkveri",
  "Tazzelenghe",
  "Tempranillo Blanco",
  "Tempranillo",
  "Tequila",
  "Teroldego",
  "Terrantez",
  "Terret Blanc",
  "Terret Gris",
  "Terret Noir",
  "Tibouren",
  "Timorasso",
  "Tinta Amarela (Trincadeira)",
  "Tinta Barroca",
  "Tinta Barroca-Tinta Roriz-Touriga",
  "Tinta Caiada",
  "Tinta Carvalha",
  "Tinta Francisca",
  "Tinta Negra Mole",
  "Tinta Roriz (Aragonez)-Touriga",
  "Tinta Roriz-Tinto Cao-Touriga",
  "Tintilia",
  "Tinto Cao",
  "Tintore di Tramonti",
  "Titan",
  "Tokaji Blend",
  "Torbato",
  "Torrontes",
  "Touriga Franca",
  "Touriga Franca-Touriga Nacional",
  "Touriga Nacional",
  "Trajadura (Treixadura)",
  "Traminer",
  "Traminette",
  "Trbljan",
  "Trebbiano (Ugni Blanc)",
  "Trebbiano Abruzzese",
  "Trebbiano Spoletino",
  "Trepat",
  "Trincadeira das Pratas",
  "Triomphe",
  "Trousseau (Bastardo)",
  "Trousseau Gris",
  "Tsaoussi",
  "Tsitska",
  "Tsolikouri",
  "Turan (Agria)",
  "Usakhelauri",
  "Uva Longanesi",
  "Uva Rara",
  "Uva del Fantini",
  "Uva di Troia",
  "Vaccarese",
  "Valdiguie",
  "Valiant",
  "Valpolicella Blend",
  "Ventura",
  "Verdanel",
  "Verdea",
  "Verdeca",
  "Verdejo",
  "Verdejo-Viura",
  "Verdelet",
  "Verdelho",
  "Verdesse",
  "Verdicchio",
  "Verdil",
  "Verdiso",
  "Verdoncho",
  "Verduzzo",
  "Vermentino (Rolle)",
  "Vermentino Nero",
  "Vermouth",
  "Vernaccia Nera",
  "Vernaccia",
  "Vertzami",
  "Vespaiolo",
  "Vespolina",
  "Vidadillo (Crespiello)",
  "Vidal",
  "Vidiano",
  "Vien de Nus",
  "Vijariego Blanco",
  "Vijariego Negro",
  "Vilana",
  "Villard Blanc",
  "Vin de Liqueur",
  "Vinhao (Sousao)",
  "Viognier",
  "Viosinho",
  "Vital",
  "Vitovska",
  "Vodka",
  "Vodka-Flavored",
  "Volitsa (Volidza)",
  "Voudomato",
  "Vradiano",
  "Vranac",
  "Vugava",
  "Vuillermin",
  "Welschriesling",
  "Wurzer",
  "Xarel-lo",
  "Xynisteri",
  "Xynomavro",
  "Zalema",
  "Zefir",
  "Zelen",
  "Zenit",
  "Zeta",
  "Zeus",
  "Zierfandler",
  "Zilavka",
  "Zinfandel",
  "Zlahtina",
  "Zweigelt"
]